figure
for i=1:size(o,3)
    d = o(:,:,i);
    o(:,:,i) = d-min(d(:));
end
%%
o = o./max(o(:));
for i=1:3:21
    plot(mean(mean(o(:,201:300,i:i+2),3),2));
    hold on
end
legend('248','200','100','50','25','10','5')
%%
k = 1;
test= mean(mean(o(:,201:300,k:k+2),3),2);
%
[fitresult, gof] = createFit1(test);
sigma = fitresult.c1/sqrt(2);
FWHM = 2*sqrt(2*log(2))*sigma;
FWHM = FWHM*(860/1024)

function [fitresult, gof] = createFit1(test)
%CREATEFIT1(TEST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: test
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jun-2020 16:37:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], test );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.078057773411274 449 46.2033531325166 0.0524477862751449 382 71.2819288865692];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'test', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'test', 'Interpreter', 'none' );
grid on
end
