function [fitresult, gof] = createFit(x, y, C)
%CREATEFIT1(X,Y,C)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: C
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Apr-2017 13:58:05


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x, y, C );

% Set up fittype and options.
ft = fittype( 'poly44' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'C vs. x, y', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y
% zlabel C
% grid on
% view( -179.9, 90.0 );


